services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/workspaces/lore
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - .:/workspaces/lore
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
