services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_PATH=${NODE_PATH}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ../node_modules:/workspaces/lore/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NODE_PATH=${NODE_PATH}
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - PORT=3000
    env_file: ./.env
    volumes:
      - ./frontend:/app
      - ../node_modules:/workspaces/lore/node_modules
      - /app/.next

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file: ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - mydata:/var/lib/postgresql/data

volumes:
  mydata:
